rholangweb/rholang/main/views.py
from pathlib import Path
from resource import setrlimit
from subprocess import Popen
from tempfile import TemporaryDirectory

from django import forms
from django.forms import Form
from django.shortcuts import render

import rholang.settings as cfg
from .runner import Compiler, VM, ConfigurationError, UserError


def home(request):
    examples = [
        dict(name=ex.name, src=ex.open().read())
        for ex in Path(cfg.EXAMPLES).glob('*.rho')
    ]

    if request.POST:
        compilerForm = CompilerForm(request.POST)
        if compilerForm.is_valid():
            rho = compilerForm.cleaned_data.get('rho')
            verbose = compilerForm.cleaned_data.get('verbose')

            try:
                runj = Compiler.jar_runner(Path(cfg.COMPILER_JAR), cfg.TIMEOUT,
                                           Popen)
                compiler = Compiler(runj)
            except ConfigurationError as oops:
                raise  # TODO: HTTP 500

            try:
                with TemporaryDirectory(prefix='rholang') as tmp:
                    rbl = compiler.compile_text(rho, work=Path(tmp))
                compile_error = None
            except UserError as oops:
                rbl = None
                compile_error = str(oops)

            session = None
            run_error = None

            if rbl is not None:
                vm = VM(Path(cfg.VM_LIBRARY),
                        VM.program_runner(Path(cfg.VM_PROGRAM),
                                          cfg.TIMEOUT, cfg.STACKLIMIT,
                                          setrlimit, Popen))
                try:
                    _warnings, _preamble, session = vm.run_repl(rbl, verbose)
                    run_error = None
                except UserError as oops:
                    run_error = oops.args[0]
                    session = None
    else:
        compilerForm = CompilerForm()
        rbl = "Compiler standing by..."
        compile_error = None
        session = "VM standing by..."
        run_error = None
    return render(request, "index.html", {
        "form": compilerForm,
        "examples": examples,
        "rbl_code": rbl or '',
        "compile_error": compile_error or '',
        "repl_session": session or '',
        "run_error": run_error or '',
    })


class CompilerForm(Form):
    rho = forms.CharField(widget=forms.Textarea)
    verbose = forms.BooleanField(label="Verbose", required=False)

rholangweb/rholang/main/templates/index.html
{% load staticfiles %}
{% load widget_tweaks %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>RChain Rholang REPL (PRE-ALPHA)</title>
    <!-- Bootstrap -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>

  <a href="https://github.com/rchain/rchain"><img style="position: absolute;
  top: 0; right: 0; border: 0;"
  src="https://camo.githubusercontent.com/a6677b08c955af8400f44c6298f40e7d19cc5b2d/68747470733a2f2f73332e616d617a6f6e6177732e636f6d2f6769746875622f726962626f6e732f666f726b6d655f72696768745f677261795f3664366436642e706e67"
  alt="Fork me on GitHub"
  data-canonical-src="https://s3.amazonaws.com/github/ribbons/forkme_right_gray_6d6d6d.png"></a>

  <div class="container">
    <form action="" method="POST">
        {% csrf_token %}
        <input id="hdnView" type="hidden" name="view" />
        <div class="page-header">
          <h1>Rholang Playground (PRE-ALPHA)</h1>

          <p>
            <a href="https://rholang.rchain.coop/">Rholang</a> is a
            language for writing smart contracts that run on the
            RChain virtual machine.
          </p>
        </div>
        <div class="panel panel-primary">
          <div class="panel-heading">
            <h3 class="panel-title">Rholang Source</h3>
          </div>
          <select id="examples">
            <option>...</option>
          </select>
          <div class="panel-body">
            {% render_field form.rho class="form-control" rows="16" cols="80" style="font-family: monospace;" placeholder='print(5)' %}
            <button type="submit" class="btn btn-default">Compile and Run</button>
            <br />
            <label>{{ form.verbose }} Verbose</label>
          </div>
        </div>

        <div class="panel panel-primary" id="output">
          <div class="panel-heading">
            <h3 class="panel-title">Output</h3>
          </div>
          {% if compile_error %}
          <pre class="alert alert-warning"
               >{{ compile_error }}</pre>
          {% elif run_error %}
          <pre class="alert alert-warning"
               >{{ run_error }}</pre>
          {% else %}
          <div class="panel-body">
            <ul class="nav nav-tabs" role="tablist">
              <li rol="presentation">
                <a href="#rbl"
                   aria-controls="home" role="tab"
                   data-toggle="tab">RBL Code</a>
              </li>
              <li rol="presentation" class="active">
                <a href="#repl"
                   aria-controls="home" role="tab"
                   data-toggle="tab">REPL Session</a>
              </li>
            </ul>
            <div class="tab-content">
              <p role="tabpanel" class="tab-pane" id="rbl"
                   ><code>{{ rbl_code }}</code></p>
              <pre role="tabpanel" class="tab-pane active" id="repl"
                   >{{ repl_session }}</pre>
            </div>
          </div>
          {% endif %}
        </div>
    </form>
  </div>

        <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
        <!-- Include all compiled plugins (below), or include individual files as needed -->
        <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script>
      $(document).ready(function () {
        $('#output a').click(function (e) {
          e.preventDefault()
          $(this).tab('show')
        });
        var examples = {{ examples|safe }};
        var exElt = $('#examples');
        exElt.html('<option>Examples:<' + '/option>');
        $.each(examples,
          (ix, ex) => exElt.append($("<option/>")
            .attr("value", ex.name).text(ex.name)));
        var exByName = {};
        $.each(examples, (ix, ex) => { exByName[ex.name] = ex.src; });
        exElt.change(() => {
          var name;
          $('#examples option:selected').each(
            (_ix, opt) => { name = $(opt).attr('value') });
          $('#id_rho').text(exByName[name]);
        });
      });
    </script>
</body>
</html>